Update 4merge.yml

diff --git a/.github/workflows/4merge.yml b/.github/workflows/4merge.yml
--- a/.github/workflows/4merge.yml
+++ b/.github/workflows/4merge.yml
@@ -14,10 +14,30 @@ concurrency:
 jobs:
   pdf-merger:
     runs-on: ubuntu-latest
+    env:
+      WORK_DIR_FILE: "${{ secrets.PRIVATE_DIR }}/myPDF工作目录.v"  # 工作目录配置文件路径
+
     steps:
-      - name: 设置工作目录环境变量
-        run: echo "WORK_DIR=${{ secrets.PRIVATE_DIR }}/cb202501" >> $GITHUB_ENV
-    
+      - name: Checkout private repo
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ secrets.PRIVATE_REPO }}
+          token: ${{ secrets.PAT }}
+          path: private-repo
+          ref: main
+
+      - name: Read WORK_DIR from file
+        id: read_work_dir
+        run: |
+          # 读取文件内容，忽略空白行和以 # 开头的行
+          WORK_DIR=$(grep -v -e '^#' -e '^$' "private-repo/$WORK_DIR_FILE" | head -n 1)
+          if [ -z "$WORK_DIR" ]; then
+            echo "Error: No valid WORK_DIR found in $WORK_DIR_FILE"
+            exit 1
+          fi
+          echo "WORK_DIR: $WORK_DIR"
+          echo "WORK_DIR=private-repo/$WORK_DIR" >> $GITHUB_ENV
+
       - name: 设置工作目录环境变量
         run: |
           echo "SOURCE_DIR=$WORK_DIR/3查找" >> $GITHUB_ENV
@@ -30,14 +50,6 @@ jobs:
           echo "源目录是：$SOURCE_DIR"
           echo "目标目录是：$OUTPUT_DIR"
           echo "查找单号文件是：$SEARCH_FILE"
-
-      - name: Checkout private repo
-        uses: actions/checkout@v4
-        with:
-          repository: ${{ secrets.PRIVATE_REPO }}
-          token: ${{ secrets.PAT }}
-          path: private-repo
-          ref: main
 
       - name: Install Ghostscript
         run: |
